[package]
name = "riscv_emu_rust_cli"
version = "0.1.0"
authors = ["Takahiro", "Tommy Thorn <tommy-github2@thorn.ws>"]
edition = "2021"

[dependencies]
libc = "0.2.155"
termios = "0.3.3"
getopts = "0.2"
riscv_emu_rust = {path = "../"}
env_logger = "0.11.7"
