[package]
edition = "2021"
name = "simmerv_wasm"
version = "0.1.0"
authors = ["Takahiro"]

[dependencies]
wasm-bindgen = "*"
simmerv = {path = "../"}

[lib]
name = "simmerv_wasm"
path = "src/lib.rs"
crate-type = ["cdylib"]
