name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build -r --all
    - name: test one
      run: cargo r -q --bin sim -- riscv-tests/passes/rv64ui-p-simple -n
    - name: Run tests
      run: cargo test --all
    - name: Run riscv-tests
      run: ./run-riscv-tests.sh
